spring.application.name=notification-service

server.servlet.context-path=/notification

server.port=9097

spring.datasource.url=jdbc:postgresql://notification-db:5432/notificationsDB
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jackson.mapper.sort-properties-alphabetically=false

#eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=127.0.0.1
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
