spring.application.name=user-service

server.servlet.context-path=/user

server.port = 9094

jwt.secretKey = ndwdfw67d5w87#e1e@jshdhja7sfywebfjyert3t

spring.datasource.url=jdbc:postgresql://user-db:5432/usersDB
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.jackson.mapper.sort-properties-alphabetically=false

#eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=127.0.0.1
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
